---
title: "Classification Models for STAT 551 Final Project"
author: "Max Donelan & Kyle Maher"
date: today
format:
  html:
    self-contained: true
# documentclass: article
execute:
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

# Setup
```{r}
library(dplyr)
library(ggplot2)
library(class)  # knn
library(glmnet)  # Regularized Logistic
library(mgcv)  # Logistic GAM
set.seed(2800)
```

# Data
```{r}
data <- read.csv("data/FP_Data.csv")
df <- as.data.frame(data)
df <- df %>%
  mutate(
    y_bin = ifelse(y >= 70, 1, 0),
    x8 = as.factor(x8)
  ) %>%
  select(-y)
```

```{r}
index <- sample(1:nrow(df), .8 * nrow(df))
train_df <- df[index, ]
test_df <- df[-index, ]
```

# Baseline Logistic 

```{r}
baseline_logistic <- glm(y_bin ~ ., data = train_df, family = "binomial")
pred <- predict(baseline_logistic, newdata = test_df, type = "response")
pred_class <- ifelse(pred >= .5, 1, 0)
mean(pred_class == test_df$y_bin)
table(pred_class, test_df$y_bin)
```

# Standard multiple logistic regression
<!-- From Tate with minimal changes -->

```{r}
small_logistic <- glm(y_bin ~ x1 + x3 + x5 + x7 + x8, family = binomial, data = df)
predict_probs <- predict(small_logistic, newdata = df, type = "response")
pred <- ifelse(predict_probs >=.5, 1, 0)
table(Actual= df$y_bin, Predicted = pred)
accuracy = (154+19)/200
print(accuracy)
```

# Regularized Logistic
<!-- From Tate with minimal changes -->

```{r}
# Prep data (needs to be a matrix)
mat <- as.matrix(df[,1:8])

# Get penalty term (lambda) via cross validation
# Alpha=1 implies Lasso (L1) regularization
cv <- cv.glmnet(mat, df$y_bin, family="binomial", alpha=1)
plot(cv) # For fun

# Generally the best lambda is the minimum one
lambda <- cv$lambda.min

# Use said lambda in final model
logistic_gam <- glmnet(mat, df$y_bin, family="binomial", alpha=1,lambda=lambda)

# Check model accuracy
predict_probs <- predict(logistic_gam, newx=mat, s=lambda, type="response")
predicted <- ifelse(predict_probs >=.5, 1, 0)
table(Actual= df$y_bin, Predicted = predicted)

accuracy = (156+19)/200
print(accuracy)
```

# Logistic GAM
<!-- From Tate with minimal changes -->

```{r}
gam_logr <- gam(y_bin~s(x5)+s(x7), family="binomial", data=df, method= "REML")
#summary(gam_logr)
#vif(gam_logr)

predict_probs <- predict(gam_logr, newdata=df, type="response")
predicted <- ifelse(predict_probs >=.5, 1, 0)
table(Actual= df$y_bin, Predicted = predicted)

accuracy = (156+20)/200
print(accuracy)
```

# KNN

```{r}
df_knn <- df %>%
  mutate(
    x1 = scale(x1),
    x2 = scale(x2),
    x3 = scale(x3),
    x4 = scale(x4),
    x5 = scale(x5),
    x6 = scale(x6),
    x7 = scale(x7),
    xA = ifelse(x8 == "A", 1, 0),
    xB = ifelse(x8 == "B", 1, 0),
    xC = ifelse(x8 == "C", 1, 0),
    xD = ifelse(x8 == "D", 1, 0)
  ) %>%
  select(-x8)

index <- sample(1:nrow(df_knn), .8 * nrow(df_knn))
train_df <- df_knn[index, ]
test_df <- df_knn[-index, ]

k_vals <- seq(1, 21, by = 2)
k_accuracy <- data.frame(
  k = k_vals,
  accuracy = NA
)

for (k in k_vals) {
  pred <- knn(
    select(train_df, -y_bin), 
    select(test_df, -y_bin), 
    as.factor(train_df$y_bin), 
    k = k
  )
  k_accuracy[k_accuracy$k == k, "accuracy"] <- mean(pred == test_df$y_bin)
}

best_k <- k_accuracy$k[which.max(k_accuracy$accuracy)]
pred <- knn(
  select(train_df, -y_bin), 
  select(test_df, -y_bin), 
  as.factor(train_df$y_bin), 
  k = best_k
)
mean(pred == test_df$y_bin)
table(pred, test_df$y_bin)
```


# K-Fold Validation

## Setup
```{r}
k <- 10
# Stratifiy by x8 group
df <- df %>%
  group_by(x8) %>%
  mutate(fold = sample(rep(1:k, length.out = n()))) %>%
  ungroup()

model_names <- c(
  "BaselineLogistic", 
  "LogLogistic", 
  "RegularizedLogisitc", 
  "LogisticGAM", 
  "KNN"
)

model_count <- length(model_names)
cv_stats <- data.frame(
  fold = rep(1:k, model_count),
  model = rep(model_names, each = k),
  accuracy = NA,
  fpr = NA,
  fnr = NA
)
# Accuracy
accuracy <- function(actual, predicted) {
  return(mean(actual == predicted))
}

# False Positive Rate
fpr <- function(actual, predicted) {
  return(sum(predicted == 1 & actual == 0) / sum(actual == 0))
}

# False Negative Rate
fnr <- function(actual, predicted) {
  return(sum(predicted == 0 & actual == 1) / sum(actual == 1))
}
```

## Running the Cross Validation
```{r}
for (i in 1:k) {
  train_df <- filter(df, fold != i) %>%
    select(-fold)
  test_df <- filter(df, fold == i) %>%
    select(-fold)
  
  # Baseline Logistic
  baseline_logistic <- glm(y_bin ~ ., data = train_df, family = "binomial")
  pred_prob <- predict(baseline_logistic, newdata = test_df, type = "response")
  pred <- ifelse(pred_prob >= .5, 1, 0)
  cv_stats[cv_stats$model == "BaselineLogistic", "accuracy"][i] <- accuracy(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "BaselineLogistic", "fpr"][i] <- fpr(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "BaselineLogistic", "fnr"][i] <- fnr(pred, test_df$y_bin)

  # Log Logistic
  log_logistic <- glm(
    y_bin ~ x1 + x2 + x3 + x5 + log(x6 + 3) + log(x7 + 3) + x8, 
    data = train_df,
    family = "binomial"
  )
  pred_prob <- predict(log_logistic, newdata = test_df, type = "response")
  pred <- ifelse(pred_prob >= .5, 1, 0)
  cv_stats[cv_stats$model == "LogLogistic", "accuracy"][i] <- accuracy(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "LogLogistic", "fpr"][i] <- fpr(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "LogLogistic", "fnr"][i] <- fnr(pred, test_df$y_bin)

  # Regularized Logistic
  train_mat <- as.matrix(select(train_df, -y_bin))
  test_mat <- as.matrix(select(test_df, -y_bin))
  cv <- cv.glmnet(train_mat, train_df$y_bin, family = "binomial", alpha = 1)
  lambda <- cv$lambda.min
  reg_logistic <- glmnet(train_mat, train_df$y_bin, family = "binomial", alpha = 1, lambda = lambda)
  predict_probs <- predict(reg_logistic, newx = test_mat, s = lambda, type = "response")
  pred <- ifelse(predict_probs >=.5, 1, 0)
  cv_stats[cv_stats$model == "RegularizedLogisitc", "accuracy"][i] <- accuracy(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "RegularizedLogisitc", "fpr"][i] <- fpr(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "RegularizedLogisitc", "fnr"][i] <- fnr(pred, test_df$y_bin)

  # Logistic GAM
  logistic_gam <- gam(
    y_bin ~ s(x1) + s(x2) + s(x3) + s(x5) + s(log(x6 + 3)) + s(log(x7 + 3)) + x8, 
    family = "binomial", 
    data = train_df, 
    method = "REML"
  )
  predict_probs <- predict(logistic_gam, newdata = test_df, type = "response")
  pred <- ifelse(predict_probs >=.5, 1, 0)
  cv_stats[cv_stats$model == "LogisticGAM", "accuracy"][i] <- accuracy(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "LogisticGAM", "fpr"][i] <- fpr(pred, test_df$y_bin)
  cv_stats[cv_stats$model == "LogisticGAM", "fnr"][i] <- fnr(pred, test_df$y_bin)

  # KNN
  train_df_onehot <- train_df %>% 
    mutate(
      x1 = scale(x1),
      x2 = scale(x2),
      x3 = scale(x3),
      x4 = scale(x4),
      x5 = scale(x5),
      x6 = scale(x6),
      x7 = scale(x7),
      xA = ifelse(x8 == "A", 1, 0),
      xB = ifelse(x8 == "B", 1, 0),
      xC = ifelse(x8 == "C", 1, 0),
      xD = ifelse(x8 == "D", 1, 0)
      ) %>% 
    select(-x8)
  test_df_onehot <- test_df  %>% 
    mutate(
      x1 = scale(x1),
      x2 = scale(x2),
      x3 = scale(x3),
      x4 = scale(x4),
      x5 = scale(x5),
      x6 = scale(x6),
      x7 = scale(x7),
      xA = ifelse(x8 == "A", 1, 0),
      xB = ifelse(x8 == "B", 1, 0),
      xC = ifelse(x8 == "C", 1, 0),
      xD = ifelse(x8 == "D", 1, 0)
      ) %>% 
    select(-x8)

  k_vals <- seq(1, 21, by = 2)
  k_accuracy <- data.frame(k = k_vals, accuracy = NA)

  for (k in k_vals) {
    pred <- knn(
      select(train_df_onehot, -y_bin), 
      select(test_df_onehot, -y_bin), 
      as.factor(train_df_onehot$y_bin), 
      k = k
    )
    k_accuracy[k_accuracy$k == k, "accuracy"] <- mean(pred == test_df_onehot$y_bin)
  }

  best_k <- k_accuracy$k[which.max(k_accuracy$accuracy)]
  pred <- knn(
    select(train_df_onehot, -y_bin), 
    select(test_df_onehot, -y_bin), 
    as.factor(train_df_onehot$y_bin), 
    k = best_k
  )

  cv_stats[cv_stats$model == "KNN", "accuracy"][i] <- accuracy(pred, test_df_onehot$y_bin)
  cv_stats[cv_stats$model == "KNN", "fpr"][i] <- fpr(pred, test_df_onehot$y_bin)
  cv_stats[cv_stats$model == "KNN", "fnr"][i] <- fnr(pred, test_df_onehot$y_bin)

}
```

## Adding the Python Neural Network Results

```{r}
nn_cv <- read.csv("src/04-cv/class_nn_cv_results.csv")
cv_stats <- bind_rows(cv_stats, nn_cv)
```

## Plotting the Cross Validation Metrics

```{r}
cv_stats %>%
  ggplot(aes(x = model, y = accuracy, fill = model)) +
  geom_boxplot(alpha = .8) +
  geom_jitter(width = .2) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    x = "Model",
    y = "Accuracy",
    title = "Accuracy by Model"
  )
```

```{r}
cv_stats %>%
  ggplot(aes(x = model, y = fpr, fill = model)) +
  geom_boxplot(alpha = .8) +
  geom_jitter(width = .2) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    x = "Model",
    y = "False Positive Rate",
    title = "False Positive Rate by Model"
  )
```

```{r}
cv_stats %>%
  ggplot(aes(x = model, y = fnr, fill = model)) +
  geom_boxplot(alpha = .8) +
  geom_jitter(width = .2) +
  theme_minimal() +
  theme(legend.position = "none") +
  labs(
    x = "Model",
    y = "False Negative Rate",
    title = "False Negative Rate by Model"
  )
```